#version 430

struct Particle {
    vec3 Position;
    vec3 PredictedPosition;
    vec3 Velocity;
    vec3 PressureAcceleration;

    float density;
    float pressure;

    uint Gridhash;
};

struct Fence {
    int left;
    int right;
    int bottom;
    int top;
    int front;
    int back;
};

layout(std430, binding = 0) buffer ParticleBuffer {
    Particle particles[];
};

layout(std430, binding = 7) buffer maxYBuffer{
    int maxY;
};

layout(local_size_x = 704) in;

layout(location = 0) uniform Fence fence;
layout(location = 6) uniform float dt;
layout(location = 7) uniform bool gravityEnabled;
layout(location = 8) uniform vec3 gravity;
layout(location = 9) uniform float particleRadius;
layout(location = 10) uniform float dampingRate;
layout(location = 11) uniform float smoothingRadius;

void main() {
    uint index = gl_GlobalInvocationID.x;
    if (index >= particles.length()) return;

    vec3 mini = vec3(fence.left, fence.bottom, fence.front);
    vec3 maxi = vec3(fence.right, fence.top, fence.back);

    Particle p = particles[index];

    vec3 velocity = p.Velocity + p.PressureAcceleration * dt;
    
    velocity += gravity * dt * float(gravityEnabled);

    vec3 position = p.Position + velocity * dt;

    vec3 radiusOffset = vec3(particleRadius + smoothingRadius);

    vec3 collisionMask = step(position, mini + radiusOffset) + step(maxi - radiusOffset, position);
    vec3 collisionNormal = sign(collisionMask) * 2.0 - 1.0;

    position = clamp(position, mini + radiusOffset, maxi - radiusOffset);

    velocity = mix(velocity, velocity * -dampingRate, collisionMask);

    float predictionTimestep = 1 / 120.0f;

    vec3 predictedPosition = position + velocity * predictionTimestep + gravity * 0.5f * (predictionTimestep * predictionTimestep);

    particles[index].Velocity = velocity;
    particles[index].Position = position;

    particles[index].PredictedPosition = clamp(predictedPosition, mini + radiusOffset, maxi - radiusOffset);

    if(position.y > maxY){
        atomicMax(maxY, int(position.y+1));
    }
}